name: Build OpenBLOX PS2


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Baixar Codigo
        uses: actions/checkout@v3

      - name: Compilar ELF
        run: |
          # Define os caminhos essenciais para o SDK do PS2
          export PS2DEV=/usr/local/ps2dev
          export PS2SDK=$PS2DEV/ps2sdk
          
          # Entra na pasta do motor
          cd C_Engine
          
          # Executa o make forçando o compilador (CC) e as pastas (SDK)
          # Tenta usar o caminho padrão do ee-gcc no contêiner
          make ps2 CC=/usr/local/ps2dev/ee/bin/ee-gcc PS2SDK=$PS2SDK
          
          
