name: Build OpenBLOX PS2


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Instalar Dependencias
        run: |
          apk update && apk add make findutils

      - name: Baixar Codigo
        uses: actions/checkout@v3

      - name: Debug e Compilar
        run: |
          echo "--- Procurando o compilador ee-gcc ---"
          find / -name "ee-gcc" 2>/dev/null || echo "Não encontrado na raiz"
          
          # Tentativa de rodar o make
          export PS2DEV=/usr/local/ps2dev
          export PS2SDK=$PS2DEV/ps2sdk
          export PATH=$PATH:$PS2DEV/bin:$PS2SDK/bin:$PS2SDK/ee/bin
          
          cd C_Engine
          make ps2

      - name: Enviar ELF Gerado
        uses: actions/upload-artifact@v4
        with:
          name: openblox_ps2_elf
          path: C_Engine/*.elf
          
