name: Build OpenBLOX PS2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - name: Instalar Dependencias
        run: |
          apk update && apk add make

      - name: Baixar Codigo
        uses: actions/checkout@v3

      - name: Compilar ELF
        run: |
          # Define as variáveis de ambiente necessárias para o PS2DEV
          export PS2DEV=/usr/local/ps2dev
          export PS2SDK=$PS2DEV/ps2sdk
          export PATH=$PATH:$PS2DEV/bin:$PS2SDK/bin:$PS2SDK/ee/bin
          
          cd C_Engine
          make ps2

      - name: Enviar ELF Gerado
        uses: actions/upload-artifact@v4
        with:
          name: openblox_ps2_elf
          path: C_Engine/*.elf
          
